name: CommitChecks

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v2
      - name: Run Test
        run: swift test
